package:
    name:           omnipay-robokassa
    namespace:      hiqdev\php\merchant\robokassa
    headline:       Omnipay: RoboKassa
    title:          RoboKassa driver for Omnipay PHP payment library
    type:           library
    license:        MIT
    keywords:       php, omnipay, robokassa, merchant, payment
    description:    |
        [Omnipay](https://github.com/omnipay/omnipay) is a framework agnostic, multi-gateway payment
        processing library for PHP 5.3+.
        This package implements [RoboKassa](http://robokassa.ru/) support for Omnipay.

require:
    hiqdev/hidev-config:        "*"
    hiqdev/hidev-config-php:    "*"
